const float PI = 3.14159265359; // PI
#define MAX_POINT_LIGHTS 3 // 最大点光源数量
#define MAX_DIRECTIONAL_LIGHTS 1 // 最大平行光源数量
#define MAX_SPOT_LIGHTS 3

#define ALBEDO_MAP_INDEX 0
#define NORMAL_MAP_INDEX 1
#define METALLIC_MAP_INDEX 2
#define ROUGHNESS_MAP_INDEX 3
#define AO_MAP_INDEX 4
#define EMISSION_MAP_INDEX 5
#define ALPHA_MAP_INDEX 6
#define HEIGHT_MAP_INDEX 7